Sprint 9 Film-User-Controller and tests
facedolls/java-filmorate-fd pull request #5
Opened 2024-02-21 07:32 UTC by facedolls

Film-User-Controller and tests

2024-02-21 21:30 UTC, andrew-larkin requested changes
Привет! Отличная работа, архитектура нового функционала реализована качественно, код хорошо написан. В одном месте небольшая правка, и будем готовы двигаться дальше.

2024-02-21 21:30 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
в классе сущности не требуется делать поля final, в следующем спринте добавится БД, драйвер, который будет связывать наше приложение с ней, сделает все сам. В User тоже можно убрать

2024-02-21 23:17 UTC, facedolls commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Внёс правки в объекты Film и User

2024-02-23 09:35 UTC, facedolls commented
Sprint 9 Film-User-Controller and tests

2024-02-23 09:35 UTC, merged