Sprint 11.1 db-diagram
facedolls/java-filmorate-fd pull request #8
Opened 2024-03-06 13:12 UTC by facedolls

feature: db-diagram

2024-03-06 13:26 UTC, Gmilovidov commented
Представленная схема верно отображает связи между таблицами и подходи для выполнения заданной логике.
Например: промежуточная таблица film_genre позволяет выполнить условие, что у одного фильма может быть несколько жанров, что соответствует условию.
Есть предложение по изменению : т.к. mpa может быть только 1 у фильма, стоит его оставить в таблице film, что позволит уменьшить кол-во таблиц

2024-03-23 14:14 UTC, andrew-larkin requested changes
Привет! Отличная реализация, буквально в одном месте поправить запрос к БД, а также у тебя упали постман тесты на гите - там одна ошибка с жанрами, надо поправить обязательно.

2024-03-23 14:14 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDaoStorage.java
> +        String sqlQuery = "SELECT * FROM \"USER\" AS U WHERE U.USER_ID IN (SELECT F.USER_SECOND_ID " +
вложенные sql запросы - не очень хорошая практика, попробуй использовать JOIIN

2024-03-25 14:01 UTC, facedolls commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDaoStorage.java
> +        String sqlQuery = "SELECT * FROM \"USER\" AS U WHERE U.USER_ID IN (SELECT F.USER_SECOND_ID " +
Спасибо! Упростил запрос через JOIN'ы -  cтало даже понятнее

2024-03-25 18:18 UTC, merged